
# material:
# velocity: m/ns
#   if air is 0.3 and material is 0 -> all of the energy is reflected
#   modeling two things:
#   - refraction direction
#   - how much percentage is transmitted or reflected? (fresnel)
materials:
  # air
  - velocity: 0.3
    ambient: 1.0
    diffuse: 0.0
    specular: 1.0
  # wall stone
  - velocity: 0.0
    ambient: 1.0
    diffuse: 0.0
    specular: 3000.0

material_id_air: 0

object_materials: [
  1, # 0: HallwayGround-mesh
  3, # 1: DoorHallway1Glass-mesh
  1, # 2: HallwayWall-mesh
  2, # 3: DoorT1203Wood-mesh
  3, # 4: DoorT1203Glass-mesh
  3, # 5: DoorT1210Glass-mesh
  2, # 6: DoorT1210Wood-mesh
  2, # 7: DoorFikaWood-mesh
  3, # 8: DoorFikaGlass-mesh
  3, # 9: DoorLabGlass-mesh
  2, # 10: Bookshelf2-mesh
  2, # 11: Bookshelf-mesh
  4, # 12: Locker-mesh
  2, # 13: Workbench2-mesh
  4, # 14: Locker2-mesh
  2, # 15: Workbench-mesh
  4, # 16: Trash-mesh
  1  # 17: Building-mesh
]
